// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data.EF;

namespace WebApi.Data.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    [Migration("20210926080527_seedingdata")]
    partial class seedingdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Data.Entites.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupFieldForeinKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("FieldId");

                    b.HasIndex("GroupFieldForeinKey");

                    b.ToTable("Field");

                    b.HasData(
                        new
                        {
                            FieldId = 1,
                            Address = "HN",
                            DateCreated = new DateTime(2021, 9, 26, 15, 5, 27, 254, DateTimeKind.Local).AddTicks(9319),
                            GroupFieldForeinKey = 1,
                            Name = "A",
                            OriginPrice = 10m,
                            Price = 0m,
                            Status = true
                        },
                        new
                        {
                            FieldId = 2,
                            Address = "HN",
                            DateCreated = new DateTime(2021, 9, 26, 15, 5, 27, 255, DateTimeKind.Local).AddTicks(2860),
                            GroupFieldForeinKey = 2,
                            Name = "A",
                            OriginPrice = 10m,
                            Price = 0m,
                            Status = true
                        },
                        new
                        {
                            FieldId = 3,
                            Address = "HN",
                            DateCreated = new DateTime(2021, 9, 26, 15, 5, 27, 255, DateTimeKind.Local).AddTicks(2894),
                            GroupFieldForeinKey = 3,
                            Name = "A",
                            OriginPrice = 10m,
                            Price = 0m,
                            Status = true
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entites.GroupField", b =>
                {
                    b.Property<int>("GroupFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("GroupFieldId");

                    b.ToTable("GroupField");

                    b.HasData(
                        new
                        {
                            GroupFieldId = 1,
                            Address = "HN",
                            Name = "Hoang",
                            Status = true
                        },
                        new
                        {
                            GroupFieldId = 2,
                            Address = "HN",
                            Name = "VanTam",
                            Status = true
                        },
                        new
                        {
                            GroupFieldId = 3,
                            Address = "HN",
                            Name = "MinhAnh",
                            Status = true
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entites.Field", b =>
                {
                    b.HasOne("WebApi.Data.Entites.GroupField", "GroupField")
                        .WithMany("Fields")
                        .HasForeignKey("GroupFieldForeinKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupField");
                });

            modelBuilder.Entity("WebApi.Data.Entites.GroupField", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
